server {
	#listen 80 ;#ssl;
    #server_name rdkit.example.com;

    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    #    ssl_certificate "/root/cert/furland.horoshij.space/fullchain.pem";
    #    ssl_certificate_key "/root/cert/furland.horoshij.space/privkey.pem";

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;
    gzip_min_length 1000;

    # 1. Все запросы к /rdkit/ (UI + эндпоинты API)
    location /rdkit/ {
        proxy_pass http://127.0.0.1:1235/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Если клиент заходит на /rdkit без слэша на конце — редиректим на /rdkit/
    location = /rdkit {
        return 301 https://$host/rdkit/;
    }

    # 2. Клиентские файлы /cli
    location /rdkit/cli/ {
        alias /opt/chem/RDKITJsme/examples_clients/;
        autoindex on;
    }

    # 3. Документация FastAPI
    location /docs { proxy_pass http://127.0.0.1:1235; }
    location /redoc { proxy_pass http://127.0.0.1:1235; }
    location /openapi.json { proxy_pass http://127.0.0.1:1235; }

    # 4. Быстрая отдача статических файлов напрямую через Nginx
    location /StaticFiles/ {
        alias /opt/chem/RDKITJsme/StaticFiles/;
        autoindex on;
        expires 7d;
        add_header Cache-Control "public, no-transform";
    }

    # 5. Прочие сервисы
    location / {
	    #        proxy_pass http://127.0.0.1:8000;
	    # proxy_buffering off;
	    # proxy_set_header Host $host;
	    # proxy_set_header X-Real-IP $remote_addr;
	    alias /var/www/html;
    }

    #location /reseed {
    #    alias /opt/b/back_key/seeder/output;
    #    autoindex on;
    #}
}

